# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.1.0'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test $(buildConfiguration)'
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration)'

# azure devops yaml variables -> https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azdevops&tabs=yaml%2Cbatch

# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azdevops&tabs=yaml
# Successfully created package '/home/vsts/work/1/s/Core/bin/Release/Core.0.1.0.nupkg' is default, i.e. -o '$(Build.ArtifactStagingDirectory)/Core/bin/$(buildConfiguration)'
# dn pack -c Release -p:version=0.1.0 -p:authors=myusrn -p:description="A .Net Core [Dnc] Environment Core Library. See Project Site link for more details." Core/Core.csproj
- script: dotnet pack -c $(buildConfiguration) -p:version=$(version) -p:authors=myusrn -p:description='A .Net Core [Dnc] Environment Core Library. See Project Site link for more details.' '**/Core.csproj'

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azdevops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azdevops&tabs=yaml
#- task: NuGetCommand@2
#  inputs:
#    command: pack
#    packagesToPack: '**/*.csproj'
##    packagesToPack: '**/Core.csproj'
#    versioningScheme: byEnvVar
#    versionEnvVar: version
#    buildProperties: authors='myusrn';owners='myusrn';Description='My .net core package'
##    packDestination: '$(Build.ArtifactStagingDirectory)/Core/bin/$(buildConfiguration)'

# https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azdevops&tabs=new-nav
# nuget.exe push /home/vsts/work/1/a/Core/bin/Release/Core.0.1.0.nupkg -NonInteractive -Source https://api.nuget.org/v3/index.json -ApiKey oy2mdacx642j7vavr7mqlztc4g6b4cuunae4ma6mytfbei -ConfigFile /home/vsts/work/1/Nuget/tempNuGet_16.config -Verbosity Detailed
# nuget.exe push Core/bin/Release/Core.0.1.0.nupkg -NonInteractive -Source https://api.nuget.org/v3/index.json -ApiKey oy2mdacx642j7vavr7mqlztc4g6b4cuunae4ma6mytfbei -ConfigFile /home/vsts/work/1/Nuget/tempNuGet_16.config -Verbosity Detailed
#- task: NuGetCommand@2
#  inputs:
#    command: push
#    nuGetFeedType: external
#    publishFeedCredentials: 'nuget-org-myusrn'
#    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
##    packagesToPush: '$(Build.ArtifactStagingDirectory)/Core/bin/$(buildConfiguration)/*.nupkg'
#    versioningScheme: byEnvVar
#    versionEnvVar: version
